USE lab7db;

INSERT INTO proveedor (
    razon_social,
    nombre_comercial,
    ruc,
    telefono,
    correo_electronico,
    sitio_web,
    direccion_fisica,
    pais,
    representante_legal,
    dni_representante_legal,
    tipo_proveedor,
    categoria,
    facturacion_anual_dolares,
    fecha_registro,
    ultima_actualizacion,
    estado
) VALUES
(
    'Corporación Andina',
    'Andina S.A.',
    '20123456789',
    '012345678',
    'contacto@andina.com',
    'https://andina.com',
    'Av. Siempre Viva 123',
    'Perú',
    'Juan Pérez',
    '12345678',
    'Nacional',
    'Servicios',
    50000.00,
    NOW(),
    NULL,
    TRUE
),
(
    'Tech Global Inc',
    'TechG',
    '20987654321',
    '098765432',
    'ventas@techg.com',
    'https://techg.com',
    'Calle Global 456',
    'Estados Unidos',
    'Anna Smith',
    '87654321',
    'Internacional',
    'Tecnología',
    150000,
    NOW(),
    NULL,
    TRUE
),
(
    'Soluciones Médicas SAC',
    'MedSol',
    '20445566778',
    '987654321',
    'info@medsol.com.pe',
    'https://medsol.com.pe',
    'Jr. Salud 789',
    'Perú',
    'Carlos Ruiz',
    '45678901',
    'Nacional',
    'Productos',
    75000,
    NOW(),
    NULL,
    TRUE
);
